FROM runpod/worker-sglang:2.0.2
RUN pip install transformers==5.8.1
RUN sed -i 's/PACKAGE_DISTRIBUTION_MAPPING\["flash_attn"\]/\["flash_attn"\]/g' /usr/local/lib/python3.12/dist-packages/transformers/utils/import_utils.py
